pub mod start_screen;
pub mod check_internet;
pub mod no_internet;
pub mod link_machine;
pub mod configure_machine;
pub mod setup_success;
pub mod setup_failed;
pub mod machine_info;
pub mod timeout_screen;